### PR TITLE
undo regression

### LINKED ISSUE #65: Fix post request to `/new` when creating a new survey
[merge conflict](https://github.com/vikrambombhi/SimpleSurvey/pull/63/files#r395635138) gone wrong

### PR DESCRIPTION
**Pull request by dipshit**
closes #65

### CODE REVIEW

File: client/src/components/SurveyForm.js [hunk 1]
```diff
@@ -13,8 +13,15 @@ export function SurveyForm({ questions }) {
     }
 
     async function submit() {
-      const res = await fetch(`/api/new?name=${name}`, {
-        method: "POST"
+      const res = await fetch(`/api/new`, {
+        method: "POST",
+        headers: {
+          Accept: "application/json",
```
Comment (bkzhang) [inline client/src/components/SurveyForm.js]: Accept should be a string
